apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: confluent-crd-reader
  namespace: dp-1-867
rules:
- apiGroups: ["platform.confluent.io"]
  resources:
    - kafkatopics
    - kafkarestproxies
    - kafkarestclasses
    - kraftcontrollers
    - kraftmigrationjobs
    - cmfrestclasses
    - ksqldbs
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: confluent-crd-reader-binding
  namespace: dp-1-867
subjects:
- kind: ServiceAccount
  name: confluent-for-kubernetes
  namespace: dp-1-867
roleRef:
  kind: Role
  name: confluent-crd-reader
  apiGroup: rbac.authorization.k8s.io
