apiVersion: v1
kind: Secret
metadata:
  name: credential
  namespace: confluent
type: Opaque
stringData:
  plain.txt: |
    username={{ .Values.kafkaAuth.username }}
    password={{ .Values.kafkaAuth.password }}

  plain-users.json: |
    {
      "{{ .Values.kafkaAuth.username }}": "{{ .Values.kafkaAuth.password }}"
    }

---
apiVersion: v1
kind: Secret
metadata:
  name: credential-plain
  namespace: confluent
type: Opaque
stringData:
  plain-jaas.conf: |
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="{{ .Values.kafkaAuth.username }}" \
    password="{{ .Values.kafkaAuth.password }}" \
    user_{{ .Values.kafkaAuth.username }}="{{ .Values.kafkaAuth.password }}";
