apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  dataVolumeCapacity: 10G
  image:
    application: docker.io/confluentinc/cp-server:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  replicas: 3
  listeners:
    controller:
      authentication:
        type: plain
        jaasConfig:
          secretRef: credential
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  image:
    application: confluentinc/cp-server:7.9.0
    init: confluentinc/confluent-init-container:2.11.0
  dataVolumeCapacity: 10Gi
  replicas: 3
  listeners:
    internal:
      authentication:
        type: plain
        jaasConfigPassThrough:
          secretRef: credential-plain
    replication:
      authentication:
        type: plain
        jaasConfigPassThrough:
          secretRef: credential-plain
    external:
      authentication:
        type: plain
        jaasConfigPassThrough:
          secretRef: credential-plain

  configOverrides:
    server:
      - auto.create.topics.enable=false
      - auto.leader.rebalance.enable=true
      - confluent.support.metrics.enable=false
      - delete.topic.enable=true
      - log.retention.check.interval.ms=300000
      - log.retention.hours=168
      - log.segment.bytes=1073741824
      - num.io.threads=8
      - num.network.threads=3
      - num.partitions=2
      - num.recovery.threads.per.data.dir=2
      - offsets.retention.minutes=1440000
      - offsets.topic.replication.factor=1
      - transaction.state.log.replication.factor=1
      - transaction.state.log.min.isr=1
      - socket.receive.buffer.bytes=102400
      - socket.request.max.bytes=104857600
      - socket.send.buffer.bytes=102400
      - session.timeout.ms=60000
      - fetch.max.wait.ms=70000
      - listener.name.controller.plain.sasl.jaas.config=${file:/mnt/secrets/credential-plain/plain-jaas.conf:sasl.jaas.config}
      - authorizer.class.name=org.apache.kafka.metadata.authorizer.StandardAuthorizer
      - allow.everyone.if.no.acl.found=true
      - super.users=User:admin;User:client

  authorization:
    type: simple

  metricReporter:
    enabled: false

  dependencies:
    kRaftController:
      controllerListener:
        authentication:
          type: plain
          jaasConfig:
            secretRef: credential
      clusterRef:
        name: kraftcontroller
    kafkaRest:
      authentication:
        type: bearer
        bearer:
          secretRef: mds-client
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: default
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demotopic
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: default
  replicas: 3
  partitionCount: 4
  configs:
    cleanup.policy: "delete"