apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: kafka-ui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kafka-ui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: {{ .Values.kafkaUi.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: AUTH_TYPE
              value: "LOGIN_FORM"
            - name: SPRING_SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-auth
                  key: username
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-auth
                  key: password

            - name: KAFKA_CLUSTERS_0_NAME
              value: "local"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka:9092"

            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
              value: "PLAIN"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-sasl
                  key: sasl_jaas_config

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-auth
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.kafkaUi.auth.username | quote }}
  password: {{ .Values.kafkaUi.auth.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-sasl
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  sasl_jaas_config: |
    org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="{{ .Values.kafka.saslUsername }}" \
    password="{{ .Values.kafka.saslPassword }}";
