apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-auth
  namespace: confluent
type: Opaque
stringData:
  username: "admin"
  password: "adminpass"
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-ui-sasl
  namespace: confluent
type: Opaque
stringData:
  sasl_jaas_config: |
    org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="kafka" \
    password="kafka-secret";
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: confluent
  labels:
    app.kubernetes.io/name: kafka-ui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kafka-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: confluent
  labels:
    app.kubernetes.io/name: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-ui
    spec:
      # imagePullSecrets:
      #   - name: aws-ecr-key
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:v0.7.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: AUTH_TYPE
              value: "LOGIN_FORM"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: SPRING_SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-auth
                  key: username
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-auth
                  key: password
            - name: KAFKA_CLUSTERS_0_NAME
              value: "confluent"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka.dp-1-867.svc.cluster.local:9092"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
              value: "PLAIN"
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
              valueFrom:
                secretKeyRef:
                  name: kafka-ui-sasl
                  key: sasl_jaas_config
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
